export { default as About } from "./About";
export { default as Header } from "./Header";
export { default as Title } from "./Title";
export { default as Hero } from "./Hero";
export { default as ProjectCard } from "./ProjectCard";
export { default as Contact } from "./Contact";
export { default as CircleBackground } from "./CircleBackground";
export { default as Footer } from "./Footer";
export { default as NavSocial } from "./NavSocial";
